### ISSUE TITLE
Woo! Excellent!

### ISSUE THREAD

**Issue by ology** [pncnmnp/phoenix10.1#21]
Donno how to chat with you, Parth. I just wanted to say that your improvements are fantastic. The tracks in my personal collection are named properly now, by the DJ. Woo!

-Gene

**Comment by pncnmnp** [comment]
Hehe! 😄 I'm glad you liked the improvements. Even I found them to be a significant upgrade. Frankly, I'm surprised that `ytmdl` never conducted tests to measure their accuracy.

Now that the improvements are done, let's discuss the next release. I want to improve the existing state of Phoenix 10.1 before we jump into adding new features. For example, now that we have good logs, unit tests, and decent code quality, it would be nice to concentrate on the "news" and "on this day" actions. If you have any other suggestions, I would love to hear them as well!

I've enabled a Github discussion for this repo, so it would be great to chat there. Others can chime in too. And please feel free to email me anytime you want a private conversation. You can find my email on my website: https://pncnmnp.github.io/.

**Comment by pncnmnp** [comment]
Discussion moved to https://github.com/pncnmnp/phoenix10.1/discussions/22
