### ISSUE TITLE
Allow selection by generic genere types

### ISSUE THREAD

**Issue by bornagainpenguin** [pncnmnp/phoenix10.1#6]
In addition to the ability to set songs by searching song title and artist and song title together, it might offer some simplicity to the enduser to be able to specify genre and a number of songs, which would offer a bit of randomness to the process and make listening more of a surprise.  There would need to be a way to record for lookup which songs were played previously in a log of some sort to avoid being bombarded with the same songs over and over again but it could add some variety, especially if it were possible to specify  a song, then several songs in a genre before returning to a specific song or two.

**Comment by pncnmnp** [comment]
Hi @bornagainpenguin,
I am currently working on this! See Issue #3 for more details.

**Comment by pncnmnp** [comment]
Hey @bornagainpenguin, the generic genre types are now included in the software. Check out `music-genre` in the README.

I am closing this issue for now. However, if you believe any clarifications/adjustments are necessary, please feel free to open it again. Thanks again for the suggesting this feature.
