### ISSUE TITLE
TTS ERROR

### ISSUE THREAD

**Issue by questjay** [pncnmnp/phoenix10.1#9]
![Uploading ttx.JPG…]()
am getting an error trying to install TTS on windows

**Comment by pncnmnp** [comment]
Hey @questjay!

I am happy to help you with this. However, can you please re-upload the image? I cannot open the file.

**Comment by pncnmnp** [comment]
@questjay Hey, by any chance did you see an error like this?

```
OSError: dlopen(/usr/local/lib/python3.10/site-packages/torchaudio/lib/libtorchaudio.so, 0x0006): Symbol not found: __ZN2at27getStepCallbacksUnlessEmptyENS_11RecordScopeE
  Referenced from: /usr/local/lib/python3.10/site-packages/torchaudio/lib/libtorchaudio.so
  Expected in: /usr/local/lib/python3.10/site-packages/torch/lib/libtorch_cpu.dylib
```

If you did, `pip install -U torch torchaudio --no-cache-dir` fixed it for me. [I found the fix from here](https://github.com/pytorch/audio/issues/62).

**Comment by pncnmnp** [comment]
Hey @questjay I was wondering if you have any update on this?
I am closing this issue for now, but if you feel that there are some issues, please do not hesitate to open this issue back up or create a new issue. Thanks.
